version: '3.3'
services:

  db:
    container_name: book_api-db
    image: postgres:15.2-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../.env

  redis:
    container_name: book_api-redis
    image: redis:7.0.11-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
    env_file:
      - ../.env
  
  backend:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: book_api-backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - ../.env


volumes:
  postgres_data:
    driver: local
  cache:
    driver: local